### ISSUE TITLE
Slash encoding in Reference not handled

### ISSUE THREAD

**Issue by sandorfr** [BigstickCarpet/swagger-parser#17]
When there is a Slash in a definition name ex `Product/Part` the corresponding reference is :  `$ref=#/definitions/Offer~1Pricing`. 

It appears that swagger-parser does not handle the slash escaping in references.

**Comment by BigstickCarpet** [comment]
Yeah, this is a known bug.  It's fixed in [Swagger Parser v3.0.0-alpha](https://github.com/BigstickCarpet/swagger-parser/tree/v3.0.0), which should be released in the next few weeks.  You can start using the alpha now if you want, by using `npm install swagger-parser@alpha`.

**Comment by sandorfr** [comment]
Awesome :) Thanks for the instructions for the alpha.

**Comment by BigstickCarpet** [comment]
FYI - Swagger 3.0.0 is now officially released, and it includes this fix
