### ISSUE TITLE
Problem with double quotes inside description fields

### ISSUE THREAD

**Issue by colingoldberg** [BigstickCarpet/swagger-parser#18]
Hi,

I the course of parsing Google's urlshortener api, I noticed that a number of description fields that Google apparently likes to have unescaped double quotes in, are problematic.

eg.
Under definitions.AnalyticsSnapshot.properties.browsers, the description field shows:
Top browsers, e.g. "Chrome"; sorted by (descending) click counts. Only present if this data is available.

Stringified snippet:
"definitions":{"AnalyticsSnapshot":{"properties":{"browsers":{"description":"Top browsers, e.g. "Chrome"; sorted by (descending) click counts. Only present if this data is available."

This plays havoc with my ability to save the stringified swagger file in a db (mysql) and then retrieve it afterwards. I do this after processing the swagger as an insurance in case I missed something. I suppose I could eliminate this, but I don't want to just yet. I cannot use db escape functions because they would just get handled like all the valid double quotes.

**Comment by BigstickCarpet** [comment]
[`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) should automatically escape any quotes or other special characters.  Are you seeing different behavior?

**Comment by colingoldberg** [comment]
I did see that (double) quotes were escaped.

The issue is that if it is saved in a db (mysql in my case), the 
escaping is lost - ie. an inspection of the contents of the db record 
will show the double quote but it is not escaped. So when read back, it 
barfs (thanks to Google not thinking/caring about this). Of course, 
there are utilities which all you to save safely in mysql (ie. escaping 
...), but the problem here is that ALL the double quotes would be 
treated equally - therefore not solving this problem at all. This needs 
to be solved at the level/context of the individual field. It seems 
description fields are the most likely fields to contain this kind of 
thing, although I would not guarantee this.

My (quick?) solution is to remove all double quotes within a value. So

description: "... browsers eg. "Chrome" ..."

would become

description: "... browsers eg. Chrome ..."


Regards

Colin Goldberg

**Comment by BigstickCarpet** [comment]
I don't think this is something that should be changed in Swagger Parser.  The parser's job is to faithfully parse the Swagger file.  If the source file has quotes, then the parsed object should also have quotes.

As a workaround for this particular issue, you can either strip quotes out of the file (manually or automatically) before running the parser, or you can crawl the parsed object and remove the quotes before serializing it as JSON.
