### ISSUE TITLE
Parsing YAML string?

### ISSUE THREAD

**Issue by gkoberger** [BigstickCarpet/swagger-parser#19]
Is there a way to pass in a YAML string to `parse`? You can pass a YAML file, or a JSON object, but not YAML string. If not, this would be very handy :)

(Awesome package, by the way. Thanks!)

**Comment by BigstickCarpet** [comment]
Very good idea!  I've added this to [Swagger Parser 3.0](https://github.com/BigstickCarpet/swagger-parser/tree/v3.0.0), which will be released soon.  If you want to install it now, then use `npm install swagger-parser@alpha`.

Here are the docs: https://github.com/BigstickCarpet/swagger-parser/tree/v3.0.0#yaml-object

**Comment by BigstickCarpet** [comment]
Just to clarify...  You still can't pass a YAML string to the `parse` method (or any of the other Swagger Parser methods - `resolve`, `dereference`, `validate`, etc.).   But you can pass your YAML string to `YAML.parse()` to convert it to an object, and _then_ pass that object to any of the Swagger Parser methods
