### ISSUE TITLE
How to validate only data instead of passing a file reference

### ISSUE THREAD

**Issue by ranacseruet** [BigstickCarpet/swagger-parser#21]
I want to validate swagger yaml/json that I am constructing programmatically and want to pass data to the 'validate' method instead of a file reference(don't want to write data in file and then pass its reference). 

Is there any way to do that?

**Comment by BigstickCarpet** [comment]
Yep!  You can pass an object to any of the Swagger Parser methods instead of a file path.   I mentioned it in the documentation for the [`parse` method](https://github.com/BigstickCarpet/swagger-parser/tree/v3.0.0#parsepath-options-callback), but I guess I should do a better job of point that out.
