### ISSUE TITLE
Validation: provide errors in z-schema format

### ISSUE THREAD

**Issue by IvanGoncharov** [BigstickCarpet/swagger-parser#24]
I'm thinking about switching to your library for validation purposes.
Especially since you already using it as testsuite :)
One of the things that blocks me is that I need errors in z-schema format in order to autofix them.
I don't want to parse error string because it too unreliable.

[Here](https://github.com/APIs-guru/api-models/blob/master/scripts/collection.js#L352) you can see example of my use case.

**Comment by BigstickCarpet** [comment]
Done!  Schema validation errors now have the Z-Schema `details` property, so you should be good-to-go.

BTW...  You might also be interested in [swagger-cli](https://www.npmjs.com/package/swagger-cli), which uses Swagger Parser to validate Swagger files from the command line
