### ISSUE TITLE
Update json-schema-ref-parser dependency

### ISSUE THREAD

**Issue by RomanGotsiy** [BigstickCarpet/swagger-parser#30]
Currently swagger-parser uses json-schema-ref-parser@1.4.1.
Could you please update it to use the latest version?

**Comment by BigstickCarpet** [comment]
I'm hoping to get to this this weekend.  I've been waiting to finish [this PR](https://github.com/BigstickCarpet/json-schema-ref-parser/pull/8) first.  As of [this commit](https://github.com/BigstickCarpet/json-schema-ref-parser/commit/516a703720155a3badd248cdbc5a6dee100de262), it's mostly done.  Just need to update the documentation, and find out why [some tests are failing in a few browsers](https://saucelabs.com/u/json-schema-parser)

**Comment by malko** [comment]
:+1:

**Comment by stvnmntjy** [comment]
+1.
 
`2.2.0` seems to fix a bug (according to my testing) in `1.4.1` re: _consistency_ when resolving non-local json references. in `1.4.1`, there’s non-deterministic (non-unique) results over my large sample parsing test (1000 iterations of `bundle()` yielding different definitions).

_just to give you an idea of the test…_

```javascript
var jsonSchemaRefParser = require('json-schema-ref-parser');
var _ = require('lodash');
var async = require('async');

var results = [];

async.timesSeries(1000, function (n, next) {
        'use strict';
        jsonSchemaRefParser.bundle(__dirname + '/api/index.yaml')
            .then(function (api) {
                results.push(JSON.stringify(api.definitions));
                next();
            });
    }, function (err) {
    'use strict';
    var length = results.length;
    console.log('length === 1000? ' + (length === 1000));

    var uniqArray = _.uniq(results);
    var uniqLength = uniqArray.length;
    console.log('unique length === 1? ' + (uniqLength === 1));
    console.log(uniqArray);
});
```

**Comment by RomanGotsiy** [comment]
@BigstickCarpet it blocks me. Could I help you with this?

**Comment by BigstickCarpet** [comment]
I just stabilized JSON Schema $Ref Parser v3.0.0.  So tomorrow I'll start getting Swagger Parser updated

**Comment by RomanGotsiy** [comment]
Awesome! Thanks for quick reply :)

**Comment by BigstickCarpet** [comment]
Swagger Parser v4.0 _beta_ is now available.
You can install the beta using `npm install swagger-parser@beta`.

- [v4.0 code branch](https://github.com/BigstickCarpet/swagger-parser/tree/releases/4.0.0)
- [v4.0 documentation](https://github.com/BigstickCarpet/swagger-parser/tree/releases/4.0.0/docs)
- [v4.0 changelog](https://github.com/BigstickCarpet/swagger-parser/blob/releases/4.0.0/CHANGELOG.md)

**Comment by RomanGotsiy** [comment]
Thanks, now it's fine. Closing this issue.
