### ISSUE TITLE
Spaces in $ref fields are replaced with %20

### ISSUE THREAD

**Issue by RomanGotsiy** [BigstickCarpet/swagger-parser#31]
Spaces in `$ref` field (even for local references) are replaced with `%20` after `bundle`. At the same time definitions are keep unchanged.

Check out this minimal example: https://tonicdev.com/568d54ee61bef80d0022d2a7/569a1141545e300d002fae3b

**Comment by BigstickCarpet** [comment]
This is by design.  JSON References (`$ref` pointers) are URIs - even when they point to local files - so they should be URI-encoded.  Your sample schema is _technically_ invalid, since `"$ref": "#/definitions/def with spaces"` is not properly URI-encoded.  But Swagger Parser uses [`url.parse()`](https://nodejs.org/docs/latest/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost) internally, which automatically [escapes certain characters for you](https://nodejs.org/docs/latest/api/url.html#url_escaped_characters).

**Comment by IvanGoncharov** [comment]
@BigstickCarpet I made investigation together with @RomanGotsiy and we agree that `$ref` can't have space inside. But to fully clarify how this situation I created issue at spec repo.
After confirmation, I will try to push changes that forbid space in `$ref` into JSON Schema for Swagger format.

**Comment by BigstickCarpet** [comment]
> It's really important issue because I see multiply occasion when people use spaces in names of schema objects. And it causing issues with libraries for example: BigstickCarpet/swagger-parser#31
We need to have official decision on how to handle such situations.

Just to clarify... this isn't a tooling problem.  Swagger Parser properly decodes & encodes the URI.  The only potential problem is that the Swagger 2.0 spec doesn't enforce proper encoding of spaces in URIs.  But even that isn't a big problem, since pretty much anything that parses URIs (including web browsers, Node.js, and Swagger Parser) will automatically encode invalid characters, such as spaces.

**Comment by IvanGoncharov** [comment]
@BigstickCarpet but in reality, after tool run `swagger-parser` to resolve external reference.
It will end up with url encoded `$ref`s so they valid JSON Pointers but invalid JSON References.
And most of implementations will try to work with it as JSON Reference.
I know it's not a problem of `swagger-parser`, but it very easy to make mistake.
Before reading all this specs I would also think that I can treat in-document `$ref`s as JSON References.

**Comment by BigstickCarpet** [comment]
`$ref` is _always_ a JSON Reference.   JSON Reference is _always_ a URI.   JSON Reference _may contain_ a JSON Pointer.   This may seem pedantic, but it's important for proper implementation of the spec.

The following is a _correct_ Swagger 2.0 spec:

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths: {}
definitions:
  'name with space': {}                               # <-- spaces here are fine
  schemaWithReference:
    type: array
    items:
      $ref: '#/definitions/name%20with%20space'       # <-- spaces here should be encoded
```

In this example, `"#/definitions/name%20with%20space"` is a valid JSON Reference that contains a valid JSON Pointer.   That pointer points to the definition `"name with space"`, since the pointer is decoded upon parsing.

**Comment by IvanGoncharov** [comment]
@BigstickCarpet Your implementation is totally correct. I just wanted to be sure that Ron agrees on it.
In my experience sometimes spec is ignored especially in cases when it touches JSON Schema.
I want to solve this issue on APIs.guru level and not to pass it down to API clients.
So I need to do this in a way that all parties agreed on, so if I do URL encoding all parsers should support it.

**Comment by BigstickCarpet** [comment]
Cool.  I think we're all on the same page then.  :+1:   Just wanted to be 100% sure.   I think we can close this issue then.

**Comment by IvanGoncharov** [comment]
@RomanGotsiy expirience this issue because he use APIs.guru as test suite.

> I think we can close this issue then.

Yes definitely.

**Comment by IvanGoncharov** [comment]
@BigstickCarpet It's not about this issue or `swagger-parser` I just want to ask for advice.
What if I replace all spaces with underscores both in `$ref`s and inside keys of `definitions` object?
Obviously it partial solution but currently I have problem only with spaces.
And I want to simplify integration process with APIs.guru as much as possible.
What do you think?
Could it cause any problems?

**Comment by BigstickCarpet** [comment]
I'm not sure what problem you're trying to solve.   Are you writing a script that generates Swagger files from something?  If so, can't you just call [`encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) on each `$ref`?  That will replace spaces with `%20` and will also handle any other special characters, such as `+`, `<`, `?`, etc.

**Comment by IvanGoncharov** [comment]
@BigstickCarpet I didn't explain it very good. So I try this time do better.
Currently I have 3 specs which has spaces in APIs.guru: 
http://apis-guru.github.io/api-models/clarify.io/1.0.10/swagger.json
http://apis-guru.github.io/api-models/geneea.com/1.0/swagger.json
http://apis-guru.github.io/api-models/semantria.com/4.0/swagger.json
I have script which update all of the spec at APIs.guru, so natural solution will be to do url encoding in this script. This will make all specs in my repo to have proper `$ref` values. 

But learning from experience I believe that many libraries/tools will have problems handling url encoded `$ref`s. Currently I'm speaking with companies to integrate APIs.guru into their products and some of them will never work with Swagger file not from my repo. So I want to make integration is smooth as possible and be forgiving to the clients who make mistakes such as this.

My idea for workaround is to replace all spaces with underscores both in $refs and inside keys of definitions objects. So all swagger specs from APIs.guru repo will guaranteed to not have space(even escaped) inside of `$ref`.
Obviously it purely APIs.guru issue, but I want to ask for your opinion.
Do you see any problems with such workaround?

**Comment by RomanGotsiy** [comment]
> My idea for workaround is to replace all spaces with underscores both in $refs and inside keys of definitions objects. So all swagger specs from APIs.guru repo will guaranteed to not have space(even escaped) inside of $ref

By replacing spaces in both $refs and definitions keys you technically invalidate spec. What if some client does url decoding for $refs.
If you want to make integration as smooth as possible just get rid of spaces in both $refs and definitions keys.

**Comment by BigstickCarpet** [comment]
Ah, ok.  I see the situation you're in now.  It's _not_ that you're having trouble producing _valid_ specs.  It's that you're trying to produce specs with as little cognitive overhead for your consumers as possible.  So, given that goal, I think your idea of replacing spaces with underscores is good.

**Comment by IvanGoncharov** [comment]
@BigstickCarpet Yes, you're totally right. I want to produce as much as possible additional value in using APIs.guru. That is what differ it from other catalogs like APIs.io for example.

@RomanGotsiy Sorry, I hijack this issue for off topic discussion.
I think it already solved and could be closed. Do you agree?

**Comment by RomanGotsiy** [comment]
@IvanGoncharov yes
Thanks everyone for clarification.
Closing this issue.
