### ISSUE TITLE
json parser add  rule

### ISSUE THREAD

**Issue by miccom86** [BigstickCarpet/swagger-parser#37]
I am using a swagger-parser in order to validate a special json file. I have the following error:

Swagger schema validation failed. 
  Additional properties not allowed: usbMemoryTotalBytes,flashMemoryAvailBytes,model,powerSource,firmwareVersionMain,boardVersion,supplyVoltage,serialNumber,id,runTime,vendor,boardVoltage,frequencySource,flashMemoryTotalBytes,boardTemperature,CPUFrequency,ramSize,hardwareVersion,usbMemoryAvailBytes,externalAntennaStatus at #/definitions//receiver/information//properties/information
 
JSON_OBJECT_VALIDATION_FAILED

Error: Swagger schema validation failed. 
  Additional properties not allowed: usbMemoryTotalBytes,flashMemoryAvailBytes,model,powerSource,firmwareVersionMain,boardVersion,supplyVoltage,serialNumber,id,runTime,vendor,boardVoltage,frequencySource,flashMemoryTotalBytes,boardTemperature,CPUFrequency,ramSize,hardwareVersion,usbMemoryAvailBytes,externalAntennaStatus at #/definitions//receiver/information//properties/information
 
JSON_OBJECT_VALIDATION_FAILED
    at http://127.0.0.1:8080/www/js/bundle.min.js:11:318
    at http://127.0.0.1:8080/www/js/bundle.min.js:50:316 

SyntaxError: Swagger schema validation failed. 
  Additional properties not allowed: usbMemoryTotalBytes,flashMemoryAvailBytes,model,powerSource,firmwareVersionMain,boardVersion,supplyVoltage,serialNumber,id,runTime,vendor,boardVoltage,frequencySource,flashMemoryTotalBytes,boardTemperature,CPUFrequency,ramSize,hardwareVersion,usbMemoryAvailBytes,externalAntennaStatus at #/definitions//receiver/information//properties/information
 
JSON_OBJECT_VALIDATION_FAILED
    at Function.syntax (http://127.0.0.1:8080/dist/swagger-parser.min.js:284:318)
    at validateSchema (http://127.0.0.1:8080/dist/swagger-parser.min.js:20:254)
    at http://127.0.0.1:8080/dist/swagger-parser.min.js:8:1921 

z-schema validation error: JSON_OBJECT_VALIDATION_FAILED
    at ZSchema.getLastError (http://127.0.0.1:8080/dist/swagger-parser.min.js:2047:3479)
    at validateSchema (http://127.0.0.1:8080/dist/swagger-parser.min.js:20:158)
    at http://127.0.0.1:8080/dist/swagger-parser.min.js:8:1921

The swagger validate give me those error when it tries to validate the following json lines:

   "definitions": {
        "/receiver/information/": {
            "description": "Receiver Information Resources",
            "x-permission": ["GET"],
            "properties": {
                "information": {
                    "externalAntennaStatus" :{
                        "title":"#/basic/Receiver/Information/externalAntennaStatus"
                    },
                    "usbMemoryAvailBytes" :{
                        "title":"#/basic/Receiver/Information/usbMemoryAvailBytes"
                    },
                    "hardwareVersion" : {
                        "title":"#/basic/Receiver/Information/hardwareVersion"
                    },

        . . .. . . . .. . . . .. . . .

Unfortunately I have to keep the json file as is.  I have to add a special rule in order to "validate" my special json file, without put the x-property in json file.

Where is the best place to add this special rule into swagger-parser ? How can it could be ?

I am working in local.

**Comment by Piefayth** [comment]
Hopefully someone will come along with more information, but if you still need a starting point I would look at this bit.

https://github.com/BigstickCarpet/swagger-parser/blob/ed6595c7e905e753f0bd20cc33b26b27f2474d8c/lib/validate-schema.js#L6

Currently swagger-parser is using ZSchema to validate against the [official swagger schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json). In your use case, it appears you would require a custom JSON schema in place of the one being used.

**Comment by BigstickCarpet** [comment]
It looks like the file you're parsing is not a Swagger file, so Swagger Parser isn't the right tool to be using for this.  I recommend using [JSON Schema $Ref Parser](https://github.com/BigstickCarpet/json-schema-ref-parser) instead, which has all the same features as Swagger Parser, except for the Swagger-specific stuff.
