### ISSUE TITLE
Validating yaml which is stored as an object

### ISSUE THREAD

**Issue by bhar629** [BigstickCarpet/swagger-parser#38]
Is the swagger parser capable of parsing the swagger yaml/json stored as an object in node.js?
Can you give me an example?

**Comment by BigstickCarpet** [comment]
Yep.  All of the methods, such as [`validate()`](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#validateapi-options-callback), [`dereference()`](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#dereferenceapi-options-callback), etc, take a string or an object as the first parameter.  Most of the examples show a string (URL or file path) being passed, but you can just as easily pass an object.

Here's an example: https://tonicdev.com/bigstickcarpet/swagger-parser-with-object
