### ISSUE TITLE
why .yaml? It's json schema!

### ISSUE THREAD

**Issue by ducin** [BigstickCarpet/swagger-parser#39]
Hello,

I'm starting with swagger, but I'm deeply familiar with the concept of API contracts (swagger, RAML, API Blueprint) as well as JSON Schema. I've tried your [online example](http://bigstickcarpet.com/swagger-parser) and I used to built-in petstore example:

![pet-json-schema](https://cloud.githubusercontent.com/assets/375027/13197640/27f2843a-d7f4-11e5-9a9c-e4f0f8ec8e39.png)

As far as I see, this is **not** `pet.yaml`, but `pet.json`. It's not a big difference, but it's very misleading. Especially, that what this tool generates is not just a JSON. It's JSON Schema file. And JSON schema has its own extraordinary big tool stack (far more than just swagger).

So the issue here is a wrong file extension.

**Comment by DavidBiesack** [comment]
I think this issue is obsolete - the on-line tool (I tried it today) does not list pet.yaml. (It lists  another sample but the tab does not say yaml or json)
