### ISSUE TITLE
On browser, doesn't use the right protocol and port.

### ISSUE THREAD

**Issue by zallek** [BigstickCarpet/swagger-parser#40]
When using this lib served on localhost, the lib doesn't fetch swagger urls with the right **port** and **protocol**. I investigate and the problem is in `json-schema-ref-parser`.

Some params aren't passed to `http` module which makes `http` lib resolve url to fetch according to current protocol and port.

Replacing this block at https://github.com/BigstickCarpet/json-schema-ref-parser/blob/v1.4.1/lib/read.js#L176
```JS
var req = protocol.get(
  {
    hostname: u.hostname,
    port: u.port,
    path: u.path,
    auth: u.auth
  },
  onResponse
);
```

by the following, solve the issue:
```JS
var req = protocol.get(
  {
    protocol: u.protocol,
    host: u.host,
    hostname: u.hostname,
    port: u.port,
    path: u.path,
    auth: u.auth
  },
  onResponse
);
```

**Comment by zallek** [comment]
issue created in `json-schema-ref-parser` https://github.com/BigstickCarpet/json-schema-ref-parser/issues/11

**Comment by BigstickCarpet** [comment]
This issue is fixed in newer versions of the library.  Please upgrade to the latest version, which includes many critical bug fixes, as well as many new features.
