### ISSUE TITLE
Webpack with CORS

### ISSUE THREAD

**Issue by zallek** [BigstickCarpet/swagger-parser#41]
When the fetched URL exposes the CORS header `'Access-Control-Allow-Origin': '*'`, the request fails. I investigate and the problem is in `json-schema-ref-parser`.
> A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. 

Webpack is using this lib as a http module `https://github.com/substack/http-browserify`. And for some reason, the lib set by default `xhr.withCredentials` to `true`.

Adding `withCredentials: false` on params given to http module solves the issue  https://github.com/BigstickCarpet/json-schema-ref-parser/blob/v1.4.1/lib/read.js#L176
```JS
var req = protocol.get(
  {
    hostname: u.hostname,
    port: u.port,
    path: u.path,
    auth: u.auth,
    withCredentials: false,
  },
  onResponse
);
```

**Comment by zallek** [comment]
issue created on `json-schema-ref-parser` https://github.com/BigstickCarpet/json-schema-ref-parser/issues/12

**Comment by BigstickCarpet** [comment]
This issue is fixed in newer versions of the library.  Please upgrade to the latest version, which includes many critical bug fixes, as well as many new features.
