### ISSUE TITLE
Http auth and cookie auth [enhancement]

### ISSUE THREAD

**Issue by wannabesrevenge** [BigstickCarpet/swagger-parser#43]
It would be awesome to have basic auth for http and/or pass cookies to the http request

**Comment by BigstickCarpet** [comment]
You can do this in version 4.0, which is currently in beta.  You can specify whatever HTTP headers you want via the [`resolve.http.headers` option](https://github.com/BigstickCarpet/swagger-parser/blob/releases/4.0.0/docs/options.md), including the `Set-Cookie` or `Authorization` headers.

**Comment by wannabesrevenge** [comment]
You rock! ty.
