### ISSUE TITLE
Exception 'RangeError: Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by IvanGoncharov** [BigstickCarpet/swagger-parser#5]
I'm trying to deference [swagger](https://github.com/APIs-guru/api-models/blob/master/google/drive/v2/swagger.json) file for Google Drive service.
It's actually common problem for most of [Google](https://github.com/APIs-guru/api-models/tree/master/google) services.
I disable all options except for 'resolve$Refs' option.
I observing following output:

>(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
> ...
>(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

>RangeError: Maximum call stack size exceeded

**Comment by BigstickCarpet** [comment]
Thank you for letting me know about this.  What platform are you running on (Windows, OSX, Linux)?  And what version of Node?   To find out what version of Node you're running, type `node --version` at a command prompt.

**Comment by IvanGoncharov** [comment]
>$ cat /etc/lsb-release 
>DISTRIB_ID=Ubuntu
>DISTRIB_RELEASE=14.04
>DISTRIB_CODENAME=trusty
>DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
>$ node --version
>v0.10.25

**Comment by BigstickCarpet** [comment]
I wasn't able to reproduce the same error message that you got, but I _did_ get other errors when I tested the Swagger file that you linked to.   All of those errors are now fixed and have been tested on Node 0.10.x, 0.11.x, and 0.12.x on Mac, Windows, and Linux.   Please re-test on your environment using Swagger Parser v2.2.9.  If you still get errors, please re-open this issue and I'll get 'em fixed.

Thanks!
