### ISSUE TITLE
Petstore Swagger Spec is Invalid?

### ISSUE THREAD

**Issue by arnm** [BigstickCarpet/swagger-parser#6]
I ran the parser against the [PetStore Spec](http://petstore.swagger.io/v2/swagger.json) and it was invalid. I got the following error message:

```
message: "Error in Swagger definition ↵SyntaxError: Array is too short (0), minimum 1 ↵Data path: "/paths/~1store~1inventory/get/parameters" ↵Schema path: "/properties/paths/patternProperties/^~1/properties/get/properties/parameters/minItems"↵"
```

Is this correct? I expected the example spec Swagger uses to be valid....

**Comment by BigstickCarpet** [comment]
Yeah, this was a bug in the Swagger 2.0 Schema.  It was [fixed last month](https://github.com/swagger-api/swagger-spec/issues/305), but they haven't published the updated schema to npm yet.    Maybe I should consider pulling the schema directly from their GitHub repo instead of npm.

**Comment by BigstickCarpet** [comment]
Good news!  The Swagger team updated their npm package, so do an `npm update` and this issue should be fixed.   You can also [test it online](https://bigstickcarpet.github.io/swagger-parser/)
