### ISSUE TITLE
[Question] Plans on support for OpenAPI v3

### ISSUE THREAD

**Issue by kalinchernev** [BigstickCarpet/swagger-parser#62]
Hi,
I'm one of the guys working on the `swagger-jsdoc` module which depends on `swagger-parser`  for (obviously) parsing data into swagger spec object.

It seems the new version of the specification is close to something tangible. ([RC](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.0-rc0) and some tools sprouting already) Thus, I was wondering if you plan to also support this v3, etc?

Thanks!

**Comment by BigstickCarpet** [comment]
Yep, I've been following the OAI v3 announcements, and I definitely intend to support it in Swagger Parser

**Comment by edahlseng** [comment]
What is the latest plan for supported OAS v3? The release window is coming up in the next coulee weeks, and they recommend tooling to begin working on prototypes in the meantime.

**Comment by BigstickCarpet** [comment]
While I probably won't be ready with OAS v3 support right at release time, I do plan to have something ready shortly thereafter.  I've been working on laying the groundwork for it for a few weeks now, and I'm making good progress.

**Comment by edahlseng** [comment]
That's great to hear! Is there anything I can do to help, whether contributing code or even just testing? Looking forward to seeing this feature, and happy to help wherever I can.

**Comment by MikeRalphson** [comment]
[APIs.guru](https://github.com/apis-guru/openapi-directory) will have a (initially static) OpenAPI 3.0.0 branch for testing purposes, from spec. release day.

**Comment by BigstickCarpet** [comment]
Hi guys.  I'll gladly accept help with the code and testing for OAI3.  Let me get the code to a stable point first, and then I'll publish an alpha version for feedback, testing, and bug-fixing.

**Comment by SomeoneRandom42** [comment]
Any potential timeline on the alpha version? Just trying to plan :) Thanks!

**Comment by BigstickCarpet** [comment]
Hi.  I'm hoping to have the alpha ready by the end of August.  Work has been really hectic lately, and I have a 3-week business trip coming up, so that may delay me a bit.  :-/

**Comment by WangJunru** [comment]
Hi, Any progress?

**Comment by BigstickCarpet** [comment]
You can review my progress [here](https://github.com/BigstickCarpet/json-schema-lib) and give me any feedback that you have.  I'm currently on a month-long business trip, so I haven't been able to work on it lately, but I'll get right back to it as soon as I return home in late September.

**Comment by gonenduk** [comment]
Any updates?

**Comment by BigstickCarpet** [comment]
I'm closing this issue and consolidating comments on Issue #72

**Comment by BigstickCarpet** [comment]
I just released Swagger Parser v5.0.0, which includes support for OpenAPI 3.0
