### ISSUE TITLE
Generating sample response and curl request

### ISSUE THREAD

**Issue by avivash** [BigstickCarpet/swagger-parser#66]
Hi, I'm wondering if there is a `swagger-parser` API method to populate a sample `curl` request for a swagger entrypoint or a sample response for an entrypoint? I'm looking through the API, but haven't found a way of doing this yet. I'd really appreciate any advice you can offer.

Thanks

**Comment by BigstickCarpet** [comment]
This isn't something that really belongs in swagger-parser.  But there are other tools in the Swagger ecosystem that can generate cURL commands for you.  Check out [this thread on Swagger UI](https://github.com/swagger-api/swagger-ui/issues/1073) for example.

**Comment by avivash** [comment]
Okay cool, thanks @BigstickCarpet!
