### ISSUE TITLE
Error occurred after install

### ISSUE THREAD

**Issue by daleep-croimedia** [BigstickCarpet/swagger-parser#67]
I just install swagger-parser module from npm. After installation this error occurred.

Uncaught Error: Cannot find module "swagger-schema-official/schema"

/~/swagger-parser/lib/validate-schema.js
Module not found: Error: Can't resolve 'swagger-schema-official/schema' in 'E:\xampp\htdocs\newproject\node_modules\swagger-parser\lib'
resolve 'swagger-schema-official/schema' in 'E:\xampp\htdocs\newproject\node_modules\swagger-parser\lib'
  Parsed request is a module
  using description file: E:\xampp\htdocs\newproject\node_modules\swagger-parser\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file:

**Comment by BigstickCarpet** [comment]
I'm not able to reproduce the error.  `npm install swagger-parser` works fine for me.

It's possible that this was just a one-off npm error, due to something sporadic like a network hiccup while downloading the package.  Trying re-installing and see if it works.

**Comment by daleep-croimedia** [comment]
Yes it work now, may be some network occurred that time. Now it's working fine. Thanks for your hrlp.
