### ISSUE TITLE
Duplicate operationIds don't cause validation errors

### ISSUE THREAD

**Issue by YagoGG** [BigstickCarpet/swagger-parser#68]
Running `SwaggerParser.validate()` on a Swagger file with `operationId` fields that aren't unique doesn't throw any exception.

The [Swagger specification](http://swagger.io/specification/#operation-object-36) indicates that these fields *must* have unique values:

> Unique string used to identify the operation. **The id MUST be unique among all operations described in the API**. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

(Emphasis mine)

**Comment by BigstickCarpet** [comment]
Good suggestion.  I'll plan to add that to the validation logic.

**Comment by marcelstoer** [comment]
I have a fix ready that I can create a PR for once the current issues with `master` are sorted out.
