### ISSUE TITLE
validateResponse does not account for specification extensions that are null

### ISSUE THREAD

**Issue by todanator** [BigstickCarpet/swagger-parser#73]
https://github.com/BigstickCarpet/swagger-parser/pull/74

A responses object with a Specification Extension with the type null will throw and error
```
Cannot read property 'headers' of null
``` 

You can see here that responses should be extendable
https://swagger.io/specification/#responsesObject

h2. Test
Example responses object
```
"responses": {
	"x-an-extension-null": null,
	"200": {}
}
```
'response' will evaluate to null here:
https://github.com/BigstickCarpet/swagger-parser/blob/master/lib/validate-spec.js#L49
And throw the error here for trying to access null.headers
https://github.com/BigstickCarpet/swagger-parser/blob/master/lib/validate-spec.js#L251

Suggest either filtering extensions or null safe access of headers.

**Comment by BigstickCarpet** [comment]
Thanks for reporting this issue and submitting a PR.  I've merged your changes, and they should be published to npm within the next few days
