### ISSUE TITLE
Failed resolving $ref pointer to #/responses/* path

### ISSUE THREAD

**Issue by timwangdev** [BigstickCarpet/swagger-parser#78]
Got SyntaxError after run swagger-cli bundle command.
``` bash
$ swagger bundle -o tmp/api.json http://some-url/swagger.yaml
SyntaxError: Error resolving $ref pointer "http://some-url/api/Auth.yaml#/responses/error".
Token "responses" does not exist.
```
swagger.yaml
```yaml
swagger: "2.0"
...
paths:
  allOf:
    - $ref: "api/Auth.yaml"
responses:
  error:
    description: Error reponse type.
    schema:
      $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    $ref: "definitions/ErrorResponse.yaml"
...
```
api/Auth.yaml
```yaml
/login:
  post:
    ...
    responses:
      default:
        $ref: "#/responses/error"
```
According to [Spec 2.0](https://swagger.io/docs/specification/2-0/describing-responses/) this usage is valid and could be successfully parsed by official `swagger-ui`.
Is there any option to disable resolving in-file $refs?

**Comment by BigstickCarpet** [comment]
`$ref` paths should be relative to the containing file, not the root file.  So, in your case, the `$ref` in `api/Auth.yaml` should be `swagger.yaml#/responses/error`.

Swagger-UI supports root-relative references for backward-compatibility reasons, even though it's not valid per [the spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-4).
