### ISSUE TITLE
Not resolving $ref with external url and definition

### ISSUE THREAD

**Issue by gwl-sourabh** [BigstickCarpet/swagger-parser#79]
Hi I am using version 3.4.2 and facing an issue. Just wondering if I am doing something wrong.

My YAML has external references like 

$ref: 'http://url.to.my.yaml#/definitions/ScheduleOfRate'

While bundling using SwaggerParser.bundle(), it looks like it simple ignores the #/definitions/ScheduleOfRate path and instead replaces the complete 'http://url.to.my.yaml' file. 

Can you tell me if I am doing something wrong or if I need to pass any additional parameter?

**Comment by BigstickCarpet** [comment]
Hmmm... that should work.  I have [tests for that](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/test/specs/external-partial/external-partial.yaml) and they pass.

Try using the latest version (4.0.1) rather than 3.x.  It may be a bug that was fixed since the 3.x version.

**Comment by tarasmineus** [comment]
@BigstickCarpet I have spent some time investigating, and it works the following (rather weird) way:

- The _first_ mention of the external file (http://url.to.my.yaml#/definitions/ScheduleOfRate) ignores the relative path and instead pastes the entire contents into the master file.
- All subsequent mentions of the external file are transformed to the local reference to the content pasted in the first reference.

remote.yml

Foo:
  a:1
Bar:
 b:2

master.yml
Foo:
- $ref: "remote.yml#/Foo"
- $ref: "remote.yml#/Bar"

Resolution result:
Foo:
- Foo:
    a:1
  Bar:
    b:2
- $ref: "#/Foo~0/Bar"

(Please note i have just typed the example for illustration, my investigations were made on a more complex piece).


Is that supposed to work like this?

Without being much involved into the topic I would prefer for the reference to resolve like a snippet, i.e. each reference is replaced with a piece of spec it references, except for circular cases.

In any case this is preventing me from creating any valid swagger specs with multiple files and i don't see any workaround.

**Comment by BigstickCarpet** [comment]
@tarasmineus - I tried to reproduce the problem you're seeing, but it works fine for me.  Please make sure you're using the latest version of Swagger Parser (v4.0.1).

For reference, here is [a complete, working code sample](https://runkit.com/bigstickcarpet/swagger-parser-issue-79) based on your sample code above

**Comment by tarasmineus** [comment]
Apparently I must have been using the older version. I can confirm that it works as expected now. In my view this issue can be closed. Thanks a lot for your help!

**Comment by BigstickCarpet** [comment]
Awesome! Great to hear that it was just a version thing 👍
