### ISSUE TITLE
Validation Errors

### ISSUE THREAD

**Issue by mshahat** [BigstickCarpet/swagger-parser#86]
Hi, 

running some of my swagger files in your tool, i received validation errors, however i don't get the same while running with editor.swagger.io , swagger-spec-validator , or swagger-cli validate ... 

any idea ? appreciate the pointers here. 

Thanks,

**Comment by BigstickCarpet** [comment]
Not all Swagger validators support (or enforce) the full specification, nor do they all perform the same validations.  So it's common to receive different validation results from different tools.   

If any of the validation errors you're getting from Swagger Parser are incorrect, then please let me know.   You can also [disable some validation options](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/options.md#validate-options) to avoid enforcing certain rules.
