### ISSUE TITLE
resolve$Refs - External $Refs only

### ISSUE THREAD

**Issue by Aleksion** [BigstickCarpet/swagger-parser#9]
is it possible to make it so, that the parser only resolves external references?
Besides validation, the parser works great for resolving external references, so that I can gather all the external files in one swagger file.

However, I would like to reference some things in the definitions part of the file, so that the file size doesn't get too big.

Thanks for doing a great job!

**Comment by BigstickCarpet** [comment]
Yep!  That's actually already on my to-do list.  Hoping to get to it next week.

**Comment by Aleksion** [comment]
Awesome! it looks like it doesn't take much more than an extra regex in the resolve.js and an extra check. +1 for making your code super easy to comprehend ;)

Looking forward to it. I'll keep working on my API then :D

**Comment by Aleksion** [comment]
Any updates on this? :D

**Comment by BigstickCarpet** [comment]
Hi, sorry for the delay.  I've been working crazy hours at work for the past few weeks, so I haven't had any free time to work on this.   But my schedule is back to normal now, so I'll be starting on it tonight.

**Comment by BigstickCarpet** [comment]
I've added a new option: `dereferenceInternal$Refs`.  As with all the other options, it's `true` by default.  But setting it to `false` will result in only _external_ $refs being dereferenced.

**Comment by Aleksion** [comment]
Awesome!
I'll update and test it right away :)
