### ISSUE TITLE
Successfully validates yaml file with invalid response code.

### ISSUE THREAD

**Issue by ShwetaManekari** [BigstickCarpet/swagger-parser#90]
Hello All,
As it mentioned Swagger-parser supports openAPI 3.0 specification, so I am currently using openapi3.0 specification. It validates valid yaml file which is in openAPI3.0 but when i am trying to produce error by giving invalid response code in it. Then also it is successfully validates the yaml file without errors. Please refer the below snapshot for invalid response code :
![image](https://user-images.githubusercontent.com/40655732/42933843-7308eb7e-8b63-11e8-9b1a-e5b7bfeb8097.png)

The output for invalid response code : 
![image](https://user-images.githubusercontent.com/40655732/43064079-85d545c0-8e7b-11e8-8cd6-6f6c4c6486bb.png)

Executed with **npm run mocha** command.

**Comment by BigstickCarpet** [comment]
Swagger Parser uses [`openapi-schema-validation`](https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-schema-validation) for its OpenAPI 3.0 validation.  It appears that their schema currently allows invalid HTTP response codes.  Please [open an issue](https://github.com/kogosoftwarellc/open-api/issues) or [submit a PR](https://github.com/kogosoftwarellc/open-api/pulls) on that repo.

Here is sample code that demonstrates this issue:
https://runkit.com/bigstickcarpet/swagger-parser-issue-90
