### ISSUE TITLE
Unable to resolve $ref pointer

### ISSUE THREAD

**Issue by throth** [BigstickCarpet/swagger-parser#94]
Hi,

there are already several issues about this problem, but I do not get it working.

This is what I call (my package.json is located in "e:/path1/path2/"):
`SwaggerParser.validate("specs/REST_API_Specification.yaml", {...})`

...and this is what I get:

`Unable to resolve $ref pointer \"e:/path1/path2/specs/REST_API_Specification.yaml\"`

I tried several things but nothing helped.
Any idea how to solve this?

Thanks

**Comment by throth** [comment]
Leave a comment

**Comment by throth** [comment]
Adding "validate" section to options causes this problem!!!
I removed it and everything works fine.

**Comment by throth** [comment]
Easy to reproduce. Follow the example: https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/options.md

The example code starts with 
`SwaggerParser.validate("my-api.yaml", {...`
and the options contain
`...
resolve: {
    file: false,
...
`
"my-api.yaml" was in my case a local file. This did not work.

What helped was:
`
resolve: {
  file: {
    canRead: true
  }
},
...
`

**Comment by BigstickCarpet** [comment]
Right.  The example specifically shows how to **disable** the ability to resolve local file references. 

```javascript
resolve: {
    file: false,                    // Don't resolve local file references
```

So of course with this option disabled, it won't work with a local file.
